# Contains datasets to enter into video game database

games_data = [
    (1, "007: Agent Under Fire", 4, "3/12/2002", 8.1),
    (2, "007: Everything or Nothing", 2, "2/17/2004", 9.0),
    (3, "007: Nightfire", 4, "11/19/2002", 8.5),
    (4, "50 Cent: Bulletproof", 1, "11/17/2005", 6.8),
    (5, "Super Monkey Ball Deluxe", 4, "3/15/2005", 9.2),
    (6, "Alias", 1, "4/7/2004", 8.0),
    (7, "AstroPop Deluxe", 1, "4/6/2004", 8.0),
    (8, "Auto Modellista", 2, "1/20/2004", 6.9),
    (9, "Animal Crossing", 1, "9/16/2002", 9.2),
    (10, "Army Men: Sarge's War", 4, "7/20/2004", 7.2),
    (11, "Avatar: The Last Airbender", 1, "10/10/2006", 7.0),
    (12, "Barbarian", 4, "6/27/2002", 10.0),
    (13, "Batman: Rise of Sin Tzu", 2, "10/16/2003", 7.5),
    (14, "Battlefield 2: Modern Combat", 24, "10/24/2005", 8.9),
    (15, "Baldur's Gate: Dark Alliance", 2, "10/22/2002", 9.4),
    (16, "Baten Kaitos: Eternal Wings and the Lost Ocean", 1, "11/16/2004", 8.0),
    (17, "Baten Kaitos: Origins", 1, "9/25/2006", 7.5)]

developer = [
    (1, "Electronic Arts Canada", "1992", False),
    (2, "Electronic Arts Redwood Shores Studio", "1982", False),
    (3, "Eurocom Developments Ltd", "1988", False),
    (4, "Savage Entertainment, LLC", "1997", False),
    (5, "Genuine Games, Inc.", "1998", False),
    (6, "Amusement Vision, Ltd.", "2011", False),
    (7, "Acclaim Studios Cheltenham", "1984", False),
    (8, "PopCap Games, Inc.", "2000", False),
    (9, "Capcom Production Studio 1", "1999", False),
    (10, "Nintendo EAD", "1983", True),
    (11, "3DO Company, The", "1991", False),
    (12, "AWE Games", "1992", False),
    (13, "Saffire, Inc", "1993", False),
    (14, "Ubisoft Divertissements Inc.", "1997", False),
    (15, "Electronic Arts UK Ltd.", "1995", False),
    (16, "Digital Illusions CE AB", "1992", False),
    (17, "Snowblind Studios, Inc.", "1997", False),
    (18, "tri-Crescendo Inc.", "1999", False),
    (19, "Monolith Software, Inc.", "1999", True)]

publisher = [
    (1, "Electronic Arts, Inc.", "1982", False),
    (2, "Vivendi Universal Games, Inc.", "1996", False),
    (3, "SEGA of America, Inc.", "1960", False),
    (4, "Acclaim Entertainment, Inc.", "1987", False),
    (5, "PopCap Games, Inc.", "2000", False),
    (6, "Capcom Co., Ltd.", "1979", False),
    (7, "Nintendo of America Inc.", "1980", True),
    (8, "Global Star Software Inc.", "1995", False),
    (9, "THQ Inc.", "1989", False),
    (10, "Titus Software Corporation", "1985", False),
    (11, "Ubisoft Entertainment SA", "1986", False),
    (12, "Interplay Entertainment Corp.", "1983", False),
    (13, "Namco Hometek Inc.", "1955", False)]

games_developers_publishers_data = [
    ("007: Agent Under Fire", "Electronic Arts Canada", "Electronic Arts, Inc."),
    ("007: Agent Under Fire", "Electronic Arts Redwood Shores Studio", "Electronic Arts, Inc."),
    ("007: Everything or Nothing", "Electronic Arts Redwood Shores Studio", "Electronic Arts, Inc."),
    ("007: Nightfire", "Eurocom Developments Ltd", "Electronic Arts, Inc."),
    ("007: Nightfire", "Savage Entertainment, LLC", "Electronic Arts, Inc."),
    ("50 Cent: Bulletproof", "Genuine Games, Inc.", "Vivendi Universal Games, Inc."),
    ("Super Monkey Ball Deluxe", "Amusement Vision, Ltd.", "SEGA of America, Inc."),
    ("Alias", "Acclaim Studios Cheltenham", "Acclaim Studios Cheltenham"),
    ("AstroPop Deluxe", "PopCap Games, Inc.", "PopCap Games, Inc."),
    ("Auto Modellista", "Capcom Production Studio 1", "Capcom Co., Ltd."),
    ("Animal Crossing", "Nintendo EAD", "Nintendo of America Inc."),
    ("Army Men: Sarge's War", "3DO Company, The", "Global Star Software Inc."),
    ("Avatar: The Last Airbender", "AWE Games", "THQ Inc."),
    ("Barbarian", "Saffire, Inc", "Titus Software Corporation"),
    ("Batman: Rise of Sin Tzu", "Ubisoft Divertissements Inc.", "Ubisoft Entertainment SA"),
    ("Battlefield 2: Modern Combat", "Electronic Arts UK Ltd.", "Electronic Arts, Inc."),
    ("Battlefield 2: Modern Combar", "Digital Illusions CE AB", "Electronic Arts, Inc."),
    ("Baldur's Gate: Dark Alliance", "Snowblind Studios, Inc.", "Interplay Entertainment Corp."),
    ("Baten Kaitos: Eternal Wings and the Lost Ocean", "tri-Crescendo Inc.", "Namco Hometek Inc."),
    ("Baten Kaitos: Origins", "tri-Crescendo Inc.", "Nintendo of America Inc."),
    ("Baten Kaitos: Origins", "Monolith Software, Inc.", "Nintendo of America Inc.")]

games_and_consoles = [
    ("007: Agent Under Fire", "GameCube"),
    ("007: Agent Under Fire", "Xbox"),
    ("007: Agent Under Fire", "Playstation 2"),
    ("007: Everything or Nothing", "GameCube"),
    ("007: Everything or Nothing", "Xbox"),
    ("007: Everything or Nothing", "Playstation 2"),
    ("007: Nightfire", "GameCube"),
    ("007: Nightfire", "Xbox"),
    ("007: Nightfire", "Playstation 2"),
    ("50 Cent: Bulletproof", "Playstation 2"),
    ("50 Cent: Bulletproof", "Xbox"),
    ("Super Monkey Ball Deluxe", "Playstation 2"),
    ("Super Monkey Ball Deluxe", "Xbox"),
    ("Alias", "Playstation 2"),
    ("Alias", "Xbox"),
    ("AstroPop Deluxe", "Xbox"),
    ("Auto Modellista", "GameCube"),
    ("Auto Modellista", "Playstation 2"),
    ("Auto Modellista", "Xbox"),
    ("Animal Crossing", "GameCube"),
    ("Army Men: Sarge's War", "GameCube"),
    ("Army Men: Sarge's War", "Playstation 2"),
    ("Army Men: Sarge's War", "Xbox"),
    ("Avatar: The Last Airbender", "GameCube"),
    ("Avatar: The Last Airbender", "Playstation 2"),
    ("Avatar: The Last Airbender", "Xbox"),
    ("Barbarian", "GameCube"),
    ("Barbarian", "Playstation 2"),
    ("Barbarian", "Xbox"),
    ("Batman: Rise of Sin Tzu", "GameCube"),
    ("Batman: Rise of Sin Tzu", "PLaystation 2"),
    ("Batman: Rise of Sin Tzu", "Xbox"),
    ("Battlefield 2: Modern Combat", "Xbox"),
    ("Baldur's Gate: Dark Alliance", "GameCube"),
    ("Baldur's Gate: Dark Alliance", "Playstation 2"),
    ("Baldur's Gate: Dark Alliance", "Xbox"),
    ("Baten Kaitos: Eternal Wings and the Lost Ocean", "GameCube"),
    ("Baten Kaitos: Origins", "GameCube")]

consoles = [
    (1, "GameCube", "2001", "Nintendo", 653),
    (2, "Xbox", "2001", "Microsoft", 997),
    (3, "Playstation 2", "2000", "Sony", 4380)]

games_genre = [
    ("007: Agent Under Fire", "Action"),
    ("007: Everything or Nothing", "Action"),
    ("007: Nightfire", "Action"),
    ("007: Nightfire", "Racing / Driving"),
    ("50 Cent: Bulletproof", "Action"),
    ("Super Monkey Ball Deluxe", "Action"),
    ("Super Monkey Ball Deluxe", "Compilation"),
    ("Super Monkey Ball Deluxe", "Puzzle"),
    ("Alias", "Action"),
    ("AstroPop Deluxe", "Action"),
    ("AstroPop Deluxe", "Puzzle"),
    ("Auto Modellista", "Racing / Driving"),
    ("Animal Crossing", "Simulation"),
    ("Army Men: Sarge's War", "Action"),
    ("Avatar: The Last Airbender", "Action"),
    ("Barbarian", "Action"),
    ("Batman: Rise of Sin Tzu", "Action"),
    ("Battlefield 2: Modern Combat", "Action"),
    ("Baldur's Gate: Dark Alliance", "Role-playing (RPG)"),
    ("Baten Kaitos: Eternal Wings and the Lost Ocean", "Role-playing (RPG)"),
    ("Baten Kaitos: Origins", "Role-playing (RPG)")]

genre = [
    (1, "Action", "A video game genre that emphasizes physical challenges, including hand-eye coordination and reaction-time. The genre includes a large variety of sub-genres, such as fighting games, beat 'em ups, shooter games, and platform games. Multiplayer online battle arena and some real-time strategy games are also considered action games."),
    (2, "Racing / Driving", "Racing/Driving games allow the player to race, or drive vehicles in a leisurely manner. Racing can be done in vehicles, on mounts, on foot or in completely abstract graphics. Games with this genre needs to have racing/driving for the majority of the game, not just as a short sequence."),
    (3, "Compilation", "Denotes any package that contains a combination of game titles. \"Compilations\" are two or more games in a series (prequels/sequels) or a similar genre. \"Shovelware\" is the term given to dissimilar games packaged together, usually at a low price, to try to make up for lost or sagging profits."),
    (4, "Puzzle", "Puzzle games focus purely on solving puzzles usually without much narrative. Puzzles exist in many varieties: strategic, tactical, logical, trivia, word puzzles etc."),
    (5, "Simulation", "Simulation games can be one of many different types of simulations. What all simulations have in common is that they are more realistically modeled to real life situations and/or variables than most games. Simulation games can model a wide variety of different situations and variables, most common are: Business/Trade Simulations, Construction Simulations, Life Simulations, Management Simulations, Sports Simulations, Vehicle Simulators, War Simulations (Wargames)"),
    (6, "Role-playing (RPG)", "Role-Playing games (RPGs) belong to a varied game genre that focuses on character development. Additional aspects that are often found in RPGs are: Amassing wealth, Narrative, Tactical combat, Character development in RPGs does not necessarily happen as in traditional stories, but means the main character(s) in the game learns new abilities or improves the capabilities of old ones. Character development also includes collecting armament and/or utilities of gradually increasing power.")]
